// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_app.tsx";
import * as $1 from "./routes/crew.tsx";
import * as $2 from "./routes/dest.tsx";
import * as $3 from "./routes/index.tsx";
import * as $4 from "./routes/tech.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Navbar.tsx";

const manifest = {
  routes: {
    "./routes/_app.tsx": $0,
    "./routes/crew.tsx": $1,
    "./routes/dest.tsx": $2,
    "./routes/index.tsx": $3,
    "./routes/tech.tsx": $4,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Navbar.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
